apiVersion: v1
kind: ConfigMap
metadata:
  name: sysprep
data:
  sysprep: |
    #!/bin/sh
    echo "Pulling job config from ${CONFIG_URL}..."
    wget -O FC_CONFIG_FILE "${CONFIG_URL}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: FC_DEPLOYMENT_NAME
  labels:
    app: FC_JOB_TAG
    flowcontroljob: FC_JOB_ID
spec:
  replicas: FC_INSTANCE_COUNT
  selector:
    matchLabels:
      app: FC_JOB_TAG
  template:
    metadata:
      labels:
        app: FC_JOB_TAG
    spec:
      volumes:
      - name: configdisk
        emptyDir: {}
      - name: sysprep
        configMap:
          name: sysprep
          defaultMode: 0755
      containers:
      - name: processor
        image: FC_RUNTIME_IMAGE
        volumeMounts:
        - name: configdisk
          mountPath: "FC_CONFIG_MOUNT"
        resources:
          limits:
            cpu: 1000m
            memory: 512M
      initContainers:
      - name: initializer
        image: FC_INITER_IMAGE
        volumeMounts:
        - name: configdisk
          mountPath: "FC_CONFIG_MOUNT"
        - name: sysprep
          mountPath: /usr/local/bin
        command: ['/usr/local/bin/sysprep']
        resources:
          limits:
            cpu: 1000m
            memory: 512M
